### ISSUE TITLE
possible issue with _setListCoordinates positioning

### ISSUE THREAD

**Issue by workingVladggg** [CherniyIrtish/angular-mention-demo#1]
Hello, i wanted to use this library for a project of mine and i noticed that when placing the list of users you use the style top as coordinates.top + coordinates.height in _setListCoordinates. Is that for a particular reason because for me i have a weird offset. I would really appreciate the help. Also when i reset the form the value persists and the placeholder is also visible next time i click to write something new

**Comment by CherniyIrtish** [comment]
fixed, check pls.
